title: Data Science Salary Visualizations
description: Analyzing salary trends across Canadian provinces for data science roles
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/aymanmomin/data-science-salaries-canada
